version: '3.1'

services:
  postgres:
    image: postgres:13.10
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
